services:
  - type: web
    name: pinequest-api-staging
    runtime: node
    repo: https://github.com/pinecone-studio/pinequest-s3-e2-team-9
    branch: develop
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: checksPass
    healthCheckPath: /health
    buildFilter:
      paths:
        - apps/api/**
        - package.json
        - package-lock.json
        - tsconfig.base.json

  - type: web
    name: pinequest-api-production
    runtime: node
    repo: https://github.com/pinecone-studio/pinequest-s3-e2-team-9
    branch: main
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeployTrigger: checksPass
    healthCheckPath: /health
    buildFilter:
      paths:
        - apps/api/**
        - package.json
        - package-lock.json
        - tsconfig.base.json
